# Generated by Django 6.0 on 2026-01-02 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('current_stock', models.IntegerField(default=0)),
                ('min_stock_threshold', models.IntegerField(default=10)),
            ],
        ),
    ]
