# Generated by Django 6.0 on 2026-01-04 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_remove_order_created_at_remove_order_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('PRODUCE', 'Produce'), ('MEAT', 'Meat'), ('DRY_GOODS', 'Dry Goods'), ('CLEANING', 'Cleaning'), ('BAR', 'Bar Supplies'), ('OTHER', 'Other')], default='OTHER', max_length=50),
        ),
    ]
