# Generated by Django 6.0 on 2026-01-04 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='supplier',
            field=models.CharField(choices=[('FISH_COMPANY', 'Fish Company'), ('COSTCO', 'Costco'), ('RESTAURANT_DEPOT', 'Restaurant Depot'), ('OTHER', 'Other')], default='OTHER', max_length=50),
        ),
    ]
