# Generated by Codex to align models with new fields/choices
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_product_supplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='location',
            field=models.CharField(choices=[('BABYTUNA_SUSHI', 'BabyTuna Sushi'), ('BABYTUNA_POKI_PHO', 'BabyTuna Poki & Pho'), ('DOWNTOWN', 'Downtown'), ('UPTOWN', 'Uptown'), ('MIDTOWN', 'Midtown'), ('GENERAL', 'General')], default='GENERAL', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='restock_interval_days',
            field=models.PositiveIntegerField(default=7),
        ),
        migrations.AddField(
            model_name='product',
            name='last_ordered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='location',
            field=models.CharField(choices=[('BABYTUNA_SUSHI', 'BabyTuna Sushi'), ('BABYTUNA_POKI_PHO', 'BabyTuna Poki & Pho'), ('DOWNTOWN', 'Downtown'), ('UPTOWN', 'Uptown'), ('MIDTOWN', 'Midtown'), ('GENERAL', 'General')], default='GENERAL', max_length=50),
        ),
        migrations.AddField(
            model_name='order',
            name='note',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='source',
            field=models.CharField(choices=[('FISH_COMPANY', 'Fish Company'), ('COSTCO', 'Costco'), ('RESTAURANT_DEPOT', 'Restaurant Depot'), ('LOCAL_SUPPLIER', 'Local Supplier'), ('OTHER', 'Other')], default='OTHER', max_length=50),
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='urgency',
            field=models.CharField(choices=[('Normal', 'Normal'), ('Rush', 'Rush')], default='Normal', max_length=20),
        ),
    ]
