# Generated by Django 6.0 on 2026-01-11 21:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_backend_refresh'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='inventory.product'),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='product',
            name='supplier',
            field=models.CharField(choices=[('FISH_COMPANY', 'Fish Company'), ('COSTCO', 'Costco'), ('RESTAURANT_DEPOT', 'Restaurant Depot'), ('LOCAL_SUPPLIER', 'Local Supplier'), ('OTHER', 'Other')], default='OTHER', max_length=50),
        ),
    ]
